/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;

/**
 *
 * @author Favio
 */
public class JFrameMenuPaciente extends javax.swing.JFrame {

    /**
     * Creates new form MenuPaciente
     */
    public JFrameMenuPaciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelGeneral = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        reservarCita_btn = new javax.swing.JButton();
        buscarEspecialidad_btn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        logo_label2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        salir_btn = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        lbl_nombresPaciente = new javax.swing.JLabel();
        lbl_codigoPacien = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bg_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelGeneral.setBackground(new java.awt.Color(235, 255, 253));
        PanelGeneral.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/panelllPac.png"))); // NOI18N
        PanelGeneral.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 320, -1));

        reservarCita_btn.setBackground(new java.awt.Color(0, 153, 0));
        reservarCita_btn.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        reservarCita_btn.setForeground(new java.awt.Color(255, 255, 255));
        reservarCita_btn.setText("Reservar Cita");
        reservarCita_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        reservarCita_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelGeneral.add(reservarCita_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 170, 30));

        buscarEspecialidad_btn.setBackground(new java.awt.Color(0, 153, 0));
        buscarEspecialidad_btn.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        buscarEspecialidad_btn.setForeground(new java.awt.Color(255, 255, 255));
        buscarEspecialidad_btn.setText("Buscar Areá Medica");
        buscarEspecialidad_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buscarEspecialidad_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelGeneral.add(buscarEspecialidad_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 170, 30));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        PanelGeneral.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 170, 10));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        PanelGeneral.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 170, 10));

        logo_label2.setFont(new java.awt.Font("Roboto Black", 3, 24)); // NOI18N
        logo_label2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo turing.png"))); // NOI18N
        logo_label2.setToolTipText("");
        PanelGeneral.add(logo_label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/team.png"))); // NOI18N
        PanelGeneral.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 270, -1));

        salir_btn.setBackground(new java.awt.Color(0, 153, 0));
        salir_btn.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        salir_btn.setForeground(new java.awt.Color(255, 255, 255));
        salir_btn.setText("Salir");
        salir_btn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        salir_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelGeneral.add(salir_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 80, 30));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        PanelGeneral.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 80, 10));

        lbl_nombresPaciente.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_nombresPaciente.setText(" ");
        PanelGeneral.add(lbl_nombresPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 190, -1));

        lbl_codigoPacien.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_codigoPacien.setText(" ");
        PanelGeneral.add(lbl_codigoPacien, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 190, 20));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setText("Nombres :");
        PanelGeneral.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setText("Código :");
        PanelGeneral.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, 20));

        bg_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blue-gradient-abstract-background-blue-background-template-vector.jpg"))); // NOI18N
        PanelGeneral.add(bg_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 470, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMenuPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMenuPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMenuPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMenuPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMenuPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelGeneral;
    private javax.swing.JLabel bg_label;
    public javax.swing.JButton buscarEspecialidad_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    public javax.swing.JLabel lbl_codigoPacien;
    public javax.swing.JLabel lbl_nombresPaciente;
    private javax.swing.JLabel logo_label2;
    public javax.swing.JButton reservarCita_btn;
    public javax.swing.JButton salir_btn;
    // End of variables declaration//GEN-END:variables
}
