/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author User
 */
public class JFrameHistoriaClinicaP3 extends javax.swing.JFrame {

    /**
     * Creates new form JFrameHistoriaClinicap1
     */
    public JFrameHistoriaClinicaP3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_Sig = new javax.swing.JButton();
        btn_Atras = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtf_ImpresionGene = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtf_AntPatolog = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea8 = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        txtf_AntFarmcFrec = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTextArea9 = new javax.swing.JTextArea();
        jScrollPane12 = new javax.swing.JScrollPane();
        txtf_AntHabNociv = new javax.swing.JTextArea();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTextArea10 = new javax.swing.JTextArea();
        jScrollPane14 = new javax.swing.JScrollPane();
        txtf_AntHereditario = new javax.swing.JTextArea();
        jScrollPane16 = new javax.swing.JScrollPane();
        txtf_EFESistemas = new javax.swing.JTextArea();
        btn_guardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Sig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/NextIcon30X31.png"))); // NOI18N
        btn_Sig.setBorder(null);
        btn_Sig.setContentAreaFilled(false);
        btn_Sig.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btn_Sig, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 650, -1, -1));

        btn_Atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/NextIcon30X31Alaizq.png"))); // NOI18N
        btn_Atras.setBorder(null);
        btn_Atras.setContentAreaFilled(false);
        btn_Atras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btn_Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 650, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Evaluación por sistemas:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, 20));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Antecedentes ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Examen Físico ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, 20));

        txtf_ImpresionGene.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtf_ImpresionGene.setToolTipText("");
        jPanel1.add(txtf_ImpresionGene, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 400, 20));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Impresión General:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, 20));

        jTextArea7.setEditable(false);
        jTextArea7.setBackground(new java.awt.Color(191, 191, 191));
        jTextArea7.setColumns(5);
        jTextArea7.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTextArea7.setRows(1);
        jTextArea7.setText("           \n\n           Patológicos");
        jTextArea7.setToolTipText("");
        jTextArea7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane7.setViewportView(jTextArea7);

        jPanel1.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 130, 70));

        txtf_AntPatolog.setColumns(5);
        txtf_AntPatolog.setRows(1);
        txtf_AntPatolog.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane8.setViewportView(txtf_AntPatolog);

        jPanel1.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 450, 70));

        jTextArea8.setEditable(false);
        jTextArea8.setBackground(new java.awt.Color(191, 191, 191));
        jTextArea8.setColumns(5);
        jTextArea8.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTextArea8.setRows(1);
        jTextArea8.setText("           \n            Fármacos \n           frecuentes");
        jTextArea8.setToolTipText("");
        jTextArea8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane9.setViewportView(jTextArea8);

        jPanel1.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 130, 70));

        txtf_AntFarmcFrec.setColumns(5);
        txtf_AntFarmcFrec.setRows(1);
        txtf_AntFarmcFrec.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane10.setViewportView(txtf_AntFarmcFrec);

        jPanel1.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 450, 70));

        jTextArea9.setEditable(false);
        jTextArea9.setBackground(new java.awt.Color(191, 191, 191));
        jTextArea9.setColumns(5);
        jTextArea9.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTextArea9.setRows(1);
        jTextArea9.setText("      \n      Hábitos nocivos  \n");
        jTextArea9.setToolTipText("");
        jTextArea9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane11.setViewportView(jTextArea9);

        jPanel1.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 130, 60));

        txtf_AntHabNociv.setColumns(5);
        txtf_AntHabNociv.setRows(1);
        txtf_AntHabNociv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane12.setViewportView(txtf_AntHabNociv);

        jPanel1.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 450, 60));

        jTextArea10.setEditable(false);
        jTextArea10.setBackground(new java.awt.Color(191, 191, 191));
        jTextArea10.setColumns(5);
        jTextArea10.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTextArea10.setRows(1);
        jTextArea10.setText("           \n          Hereditarios \n");
        jTextArea10.setToolTipText("");
        jTextArea10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane13.setViewportView(jTextArea10);

        jPanel1.add(jScrollPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 130, 60));

        txtf_AntHereditario.setColumns(5);
        txtf_AntHereditario.setRows(1);
        txtf_AntHereditario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane14.setViewportView(txtf_AntHereditario);

        jPanel1.add(jScrollPane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 450, 60));

        txtf_EFESistemas.setColumns(5);
        txtf_EFESistemas.setRows(1);
        txtf_EFESistemas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane16.setViewportView(txtf_EFESistemas);

        jPanel1.add(jScrollPane16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 580, 240));

        btn_guardar.setBackground(new java.awt.Color(0, 134, 190));
        btn_guardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_guardar.setForeground(new java.awt.Color(255, 255, 255));
        btn_guardar.setText("Guardar");
        btn_guardar.setBorder(null);
        btn_guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 640, 90, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 685));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameHistoriaClinicaP3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameHistoriaClinicaP3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameHistoriaClinicaP3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameHistoriaClinicaP3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameHistoriaClinicaP3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_Atras;
    public javax.swing.JButton btn_Sig;
    public javax.swing.JButton btn_guardar;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea10;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JTextArea jTextArea9;
    public javax.swing.JTextArea txtf_AntFarmcFrec;
    public javax.swing.JTextArea txtf_AntHabNociv;
    public javax.swing.JTextArea txtf_AntHereditario;
    public javax.swing.JTextArea txtf_AntPatolog;
    public javax.swing.JTextArea txtf_EFESistemas;
    public javax.swing.JTextField txtf_ImpresionGene;
    // End of variables declaration//GEN-END:variables
}
