/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Favio
 */
public class JFrameCrearPaciente extends javax.swing.JFrame {

    /**
     * Creates new form JFramePaciente
     */
    public JFrameCrearPaciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtf_codHistoria = new javax.swing.JTextField();
        txtf_documento = new javax.swing.JTextField();
        txtf_tipDoc = new javax.swing.JTextField();
        txtf_apPat = new javax.swing.JTextField();
        txtf_apMat = new javax.swing.JTextField();
        txtf_nombres = new javax.swing.JTextField();
        txtf_sexo = new javax.swing.JTextField();
        txtf_edad = new javax.swing.JTextField();
        txtf_nomCuenta = new javax.swing.JTextField();
        txtf_contrasenia = new javax.swing.JTextField();
        btn_regresar = new javax.swing.JButton();
        btn_crear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Formulario Paciente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Courier New", 0, 18), new java.awt.Color(0, 134, 190))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel1.setText("Código Paciente");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel2.setText("Documento");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel3.setText("Tipo Documento");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel4.setText("Apellido Paterno");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel5.setText("Apellido Materno");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel6.setText("Nombres");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel7.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel7.setText("Sexo");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel8.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel8.setText("Edad");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        jLabel9.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel9.setText("Nombre Cuenta");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        jLabel10.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jLabel10.setText("Contraseña");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        txtf_codHistoria.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txtf_codHistoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 140, -1));

        txtf_documento.setBackground(new java.awt.Color(204, 204, 204));
        txtf_documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtf_documentoActionPerformed(evt);
            }
        });
        jPanel1.add(txtf_documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 140, -1));

        txtf_tipDoc.setBackground(new java.awt.Color(204, 204, 204));
        txtf_tipDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtf_tipDocActionPerformed(evt);
            }
        });
        jPanel1.add(txtf_tipDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 140, -1));

        txtf_apPat.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txtf_apPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 140, -1));

        txtf_apMat.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txtf_apMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 140, -1));

        txtf_nombres.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txtf_nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 140, -1));

        txtf_sexo.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txtf_sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 140, -1));

        txtf_edad.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txtf_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 140, -1));

        txtf_nomCuenta.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txtf_nomCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 140, -1));

        txtf_contrasenia.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(txtf_contrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 140, -1));

        btn_regresar.setBackground(new java.awt.Color(0, 134, 190));
        btn_regresar.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        btn_regresar.setForeground(new java.awt.Color(255, 255, 255));
        btn_regresar.setText("Regresar");
        btn_regresar.setBorder(null);
        btn_regresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btn_regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 90, 30));

        btn_crear.setBackground(new java.awt.Color(0, 134, 190));
        btn_crear.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        btn_crear.setForeground(new java.awt.Color(255, 255, 255));
        btn_crear.setText("Crear");
        btn_crear.setBorder(null);
        btn_crear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btn_crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, 100, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtf_documentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtf_documentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtf_documentoActionPerformed

    private void txtf_tipDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtf_tipDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtf_tipDocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCrearPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCrearPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCrearPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCrearPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCrearPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_crear;
    public javax.swing.JButton btn_regresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField txtf_apMat;
    public javax.swing.JTextField txtf_apPat;
    public javax.swing.JTextField txtf_codHistoria;
    public javax.swing.JTextField txtf_contrasenia;
    public javax.swing.JTextField txtf_documento;
    public javax.swing.JTextField txtf_edad;
    public javax.swing.JTextField txtf_nomCuenta;
    public javax.swing.JTextField txtf_nombres;
    public javax.swing.JTextField txtf_sexo;
    public javax.swing.JTextField txtf_tipDoc;
    // End of variables declaration//GEN-END:variables
}
