/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Color;
import java.awt.Component;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author User
 */
public class JFrameHistoriaClinicaP2 extends javax.swing.JFrame {

    /**
     * Creates new form JFrameHistoriaClinicap1
     */
    public JFrameHistoriaClinicaP2() {
        initComponents();
    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_Sig = new javax.swing.JButton();
        btn_Atras = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtf_Relatos = new javax.swing.JTextArea();
        jScrollPane8 = new javax.swing.JScrollPane();
        txtf_SignosPrin = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtf_SintomPrinc = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        txtf_TiempoEnf = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        txtf_FormaInic = new javax.swing.JTextArea();
        btn_guardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Sig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/NextIcon30X31.png"))); // NOI18N
        btn_Sig.setBorder(null);
        btn_Sig.setContentAreaFilled(false);
        btn_Sig.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btn_Sig, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 650, -1, -1));

        btn_Atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/NextIcon30X31Alaizq.png"))); // NOI18N
        btn_Atras.setBorder(null);
        btn_Atras.setContentAreaFilled(false);
        btn_Atras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btn_Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 650, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Motivo de Consulta");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        jTextArea3.setEditable(false);
        jTextArea3.setBackground(new java.awt.Color(191, 191, 191));
        jTextArea3.setColumns(5);
        jTextArea3.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTextArea3.setRows(1);
        jTextArea3.setText("           \n       \n\n\n\n             Relato\n");
        jTextArea3.setToolTipText("");
        jTextArea3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane3.setViewportView(jTextArea3);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 130, 230));

        jTextArea7.setEditable(false);
        jTextArea7.setBackground(new java.awt.Color(191, 191, 191));
        jTextArea7.setColumns(5);
        jTextArea7.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTextArea7.setRows(1);
        jTextArea7.setText("           \n\n      Signos principales");
        jTextArea7.setToolTipText("");
        jTextArea7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane7.setViewportView(jTextArea7);

        jPanel1.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 130, 110));

        jTextArea4.setEditable(false);
        jTextArea4.setBackground(new java.awt.Color(191, 191, 191));
        jTextArea4.setColumns(5);
        jTextArea4.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTextArea4.setRows(1);
        jTextArea4.setText("           \n\n            Síntomas \n           principales");
        jTextArea4.setToolTipText("");
        jTextArea4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane4.setViewportView(jTextArea4);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 130, 110));

        jTextArea5.setEditable(false);
        jTextArea5.setBackground(new java.awt.Color(191, 191, 191));
        jTextArea5.setColumns(5);
        jTextArea5.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTextArea5.setRows(1);
        jTextArea5.setText("           \n           Tiempo de \n           enfermedad");
        jTextArea5.setToolTipText("");
        jTextArea5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane5.setViewportView(jTextArea5);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 130, 60));

        jTextArea6.setEditable(false);
        jTextArea6.setBackground(new java.awt.Color(191, 191, 191));
        jTextArea6.setColumns(5);
        jTextArea6.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTextArea6.setRows(1);
        jTextArea6.setText("           \n        Forma de inicio\n      de la enfermedad");
        jTextArea6.setToolTipText("");
        jTextArea6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane6.setViewportView(jTextArea6);

        jPanel1.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 130, 70));

        txtf_Relatos.setColumns(5);
        txtf_Relatos.setRows(1);
        txtf_Relatos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(txtf_Relatos);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 440, 230));

        txtf_SignosPrin.setColumns(5);
        txtf_SignosPrin.setRows(1);
        txtf_SignosPrin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane8.setViewportView(txtf_SignosPrin);

        jPanel1.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 440, 110));

        txtf_SintomPrinc.setColumns(5);
        txtf_SintomPrinc.setRows(1);
        txtf_SintomPrinc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane9.setViewportView(txtf_SintomPrinc);

        jPanel1.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 440, 110));

        txtf_TiempoEnf.setColumns(5);
        txtf_TiempoEnf.setRows(1);
        txtf_TiempoEnf.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane10.setViewportView(txtf_TiempoEnf);

        jPanel1.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 440, 60));

        txtf_FormaInic.setColumns(5);
        txtf_FormaInic.setRows(1);
        txtf_FormaInic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane11.setViewportView(txtf_FormaInic);

        jPanel1.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 440, 70));

        btn_guardar.setBackground(new java.awt.Color(0, 134, 190));
        btn_guardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_guardar.setForeground(new java.awt.Color(255, 255, 255));
        btn_guardar.setText("Guardar");
        btn_guardar.setBorder(null);
        btn_guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 640, 80, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 685));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameHistoriaClinicaP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameHistoriaClinicaP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameHistoriaClinicaP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameHistoriaClinicaP2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameHistoriaClinicaP2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_Atras;
    public javax.swing.JButton btn_Sig;
    public javax.swing.JButton btn_guardar;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    public javax.swing.JTextArea txtf_FormaInic;
    public javax.swing.JTextArea txtf_Relatos;
    public javax.swing.JTextArea txtf_SignosPrin;
    public javax.swing.JTextArea txtf_SintomPrinc;
    public javax.swing.JTextArea txtf_TiempoEnf;
    // End of variables declaration//GEN-END:variables
}
