/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author Favio
 */
public class JFrameMenuMedico extends javax.swing.JFrame {

    /**
     * Creates new form MenuMedico
     */
    public JFrameMenuMedico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        logo_label2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_salir = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        btn_VerHistCli = new javax.swing.JButton();
        btn_GenHistCli = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btn_AniadirEvol = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        lbl_nombresmedico = new javax.swing.JLabel();
        lbl_codigoMedico = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bg_label = new javax.swing.JLabel();
        btn_CancCita = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(235, 255, 253));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setText("Código :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, 20));

        logo_label2.setFont(new java.awt.Font("Roboto Black", 3, 24)); // NOI18N
        logo_label2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Logo turing.png"))); // NOI18N
        logo_label2.setToolTipText("");
        jPanel1.add(logo_label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/panelMedico recortado.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 380, 350));

        btn_salir.setBackground(new java.awt.Color(0, 153, 0));
        btn_salir.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btn_salir.setForeground(new java.awt.Color(255, 255, 255));
        btn_salir.setText("Salir");
        btn_salir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 80, 30));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 80, 10));

        btn_VerHistCli.setBackground(new java.awt.Color(0, 153, 0));
        btn_VerHistCli.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btn_VerHistCli.setForeground(new java.awt.Color(255, 255, 255));
        btn_VerHistCli.setText("Visualizar Apertura de una HC");
        btn_VerHistCli.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_VerHistCli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btn_VerHistCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 200, 30));

        btn_GenHistCli.setBackground(new java.awt.Color(0, 153, 0));
        btn_GenHistCli.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btn_GenHistCli.setForeground(new java.awt.Color(255, 255, 255));
        btn_GenHistCli.setText("Crear Apertura de una HC");
        btn_GenHistCli.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_GenHistCli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btn_GenHistCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, 200, 30));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/medical-team.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 270, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 200, 10));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 200, 10));

        btn_AniadirEvol.setBackground(new java.awt.Color(0, 153, 0));
        btn_AniadirEvol.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btn_AniadirEvol.setForeground(new java.awt.Color(255, 255, 255));
        btn_AniadirEvol.setText("Añadir Evolución a una Apertura");
        btn_AniadirEvol.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_AniadirEvol.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btn_AniadirEvol, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, 200, 30));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 200, 10));

        lbl_nombresmedico.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_nombresmedico.setText(" ");
        jPanel1.add(lbl_nombresmedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 190, -1));

        lbl_codigoMedico.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lbl_codigoMedico.setText(" ");
        jPanel1.add(lbl_codigoMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 190, 20));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setText("Nombres :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        bg_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blue-gradient-abstract-background-blue-background-template-vector.jpg"))); // NOI18N
        jPanel1.add(bg_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 500));

        btn_CancCita.setBackground(new java.awt.Color(0, 153, 0));
        btn_CancCita.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btn_CancCita.setForeground(new java.awt.Color(255, 255, 255));
        btn_CancCita.setText("Terminar la Cita");
        btn_CancCita.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_CancCita.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btn_CancCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, 120, 30));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, 120, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMenuMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMenuMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMenuMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMenuMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMenuMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg_label;
    public javax.swing.JButton btn_AniadirEvol;
    public javax.swing.JButton btn_CancCita;
    public javax.swing.JButton btn_GenHistCli;
    public javax.swing.JButton btn_VerHistCli;
    public javax.swing.JButton btn_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    public javax.swing.JLabel lbl_codigoMedico;
    public javax.swing.JLabel lbl_nombresmedico;
    private javax.swing.JLabel logo_label2;
    // End of variables declaration//GEN-END:variables
}
