/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author User
 */
public class JFrameHistoriaClinicaP1 extends javax.swing.JFrame {

    /**
     * Creates new form JFrameHistoriaClinicap1
     */
    public JFrameHistoriaClinicaP1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        btn_Sig = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtf_codigomedico = new javax.swing.JTextField();
        txtf_TipoDocumento = new javax.swing.JTextField();
        txtf_FechaApertura = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextFieldApell = new javax.swing.JTextField();
        txtf_CodigoHistClinic = new javax.swing.JTextField();
        txtf_Documento = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        btn_Atras = new javax.swing.JButton();
        jTextFieldApellMat = new javax.swing.JTextField();
        jTextFieldApell2 = new javax.swing.JTextField();
        jTextFieldApell3 = new javax.swing.JTextField();
        txtf_ApellPatern = new javax.swing.JTextField();
        txtf_ApellMatern = new javax.swing.JTextField();
        txtf_Nombres = new javax.swing.JTextField();
        txtf_Sexo = new javax.swing.JTextField();
        jTextFieldFechaNac = new javax.swing.JTextField();
        txtf_FechaNac = new javax.swing.JTextField();
        jTextFieldGrad = new javax.swing.JTextField();
        txtf_GradoInst = new javax.swing.JTextField();
        jTextFieldGrad1 = new javax.swing.JTextField();
        txtf_Edad = new javax.swing.JTextField();
        jTextFieldGrad2 = new javax.swing.JTextField();
        txtf_EstadCivil = new javax.swing.JTextField();
        jTextFieldFechaNac1 = new javax.swing.JTextField();
        txtf_LugarNaci = new javax.swing.JTextField();
        jTextFieldFechaNac2 = new javax.swing.JTextField();
        txtf_Domicilio = new javax.swing.JTextField();
        jTextFieldFechaNac3 = new javax.swing.JTextField();
        txtf_GrupEtn = new javax.swing.JTextField();
        jTextFieldGrad3 = new javax.swing.JTextField();
        txtf_Religion = new javax.swing.JTextField();
        txtf_Ocupacion = new javax.swing.JTextField();
        jTextFieldGrad4 = new javax.swing.JTextField();
        txtf_LugarProced = new javax.swing.JTextField();
        jTextFieldGrad5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldFechaNac4 = new javax.swing.JTextField();
        jTextFieldFechaNac5 = new javax.swing.JTextField();
        jTextFieldFechaNac6 = new javax.swing.JTextField();
        jTextFieldFechaNac7 = new javax.swing.JTextField();
        txtf_PRApellPat = new javax.swing.JTextField();
        txtf_PRApellMat = new javax.swing.JTextField();
        txtf_PRSexo = new javax.swing.JTextField();
        txtf_PRNombres = new javax.swing.JTextField();
        jTextFieldFechaNac8 = new javax.swing.JTextField();
        jTextFieldFechaNac9 = new javax.swing.JTextField();
        jTextFieldFechaNac10 = new javax.swing.JTextField();
        jTextFieldFechaNac11 = new javax.swing.JTextField();
        txtf_PRDirecc = new javax.swing.JTextField();
        txtf_PRNumeroCell = new javax.swing.JTextField();
        txtf_PRDoc = new javax.swing.JTextField();
        txtf_PRTipoDoc = new javax.swing.JTextField();
        btn_guardar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtf_CodigoPaciente = new javax.swing.JTextField();
        jTextFieldFechaNac12 = new javax.swing.JTextField();
        txtf_numCel = new javax.swing.JTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_Sig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/NextIcon30X31.png"))); // NOI18N
        btn_Sig.setBorder(null);
        btn_Sig.setContentAreaFilled(false);
        btn_Sig.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Sig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SigActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Sig, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 650, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("APERTURA DE HISTORIA CLÍNICA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Código de Redactor: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 20));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Fecha de la hoja de apertura: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, 20));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Código de la Historia Clínica: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 20));

        txtf_codigomedico.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtf_codigomedico.setToolTipText("");
        jPanel1.add(txtf_codigomedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 180, 20));

        txtf_TipoDocumento.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtf_TipoDocumento.setToolTipText("");
        txtf_TipoDocumento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtf_TipoDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 270, 20));

        txtf_FechaApertura.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtf_FechaApertura.setToolTipText("");
        jPanel1.add(txtf_FechaApertura, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 180, 20));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(191, 191, 191));
        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTextField1.setText(" Tipo de Documento");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 270, 20));

        jTextFieldApell.setEditable(false);
        jTextFieldApell.setBackground(new java.awt.Color(191, 191, 191));
        jTextFieldApell.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTextFieldApell.setText(" 1° Apellido");
        jTextFieldApell.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldApell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldApell, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 130, 20));

        txtf_CodigoHistClinic.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtf_CodigoHistClinic.setToolTipText("");
        jPanel1.add(txtf_CodigoHistClinic, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 180, 20));

        txtf_Documento.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtf_Documento.setToolTipText("");
        txtf_Documento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtf_Documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 280, 20));

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(191, 191, 191));
        jTextField4.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTextField4.setText(" Documento");
        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 280, 20));

        btn_Atras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/NextIcon30X31Alaizq.png"))); // NOI18N
        btn_Atras.setBorder(null);
        btn_Atras.setContentAreaFilled(false);
        btn_Atras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AtrasActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 650, -1, -1));

        jTextFieldApellMat.setEditable(false);
        jTextFieldApellMat.setBackground(new java.awt.Color(191, 191, 191));
        jTextFieldApellMat.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTextFieldApellMat.setText(" 2° Apellido");
        jTextFieldApellMat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldApellMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApellMatActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldApellMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 150, 20));

        jTextFieldApell2.setEditable(false);
        jTextFieldApell2.setBackground(new java.awt.Color(191, 191, 191));
        jTextFieldApell2.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTextFieldApell2.setText(" Nombres");
        jTextFieldApell2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldApell2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApell2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldApell2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 140, 20));

        jTextFieldApell3.setEditable(false);
        jTextFieldApell3.setBackground(new java.awt.Color(191, 191, 191));
        jTextFieldApell3.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTextFieldApell3.setText(" Sexo");
        jTextFieldApell3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldApell3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApell3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldApell3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 130, 20));

        txtf_ApellPatern.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtf_ApellPatern.setToolTipText("");
        txtf_ApellPatern.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtf_ApellPatern, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 130, 20));

        txtf_ApellMatern.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtf_ApellMatern.setToolTipText("");
        txtf_ApellMatern.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtf_ApellMatern, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 150, 20));

        txtf_Nombres.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtf_Nombres.setToolTipText("");
        txtf_Nombres.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtf_Nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 140, 20));

        txtf_Sexo.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtf_Sexo.setToolTipText("");
        txtf_Sexo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtf_Sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 130, 20));

        jTextFieldFechaNac.setEditable(false);
        jTextFieldFechaNac.setBackground(new java.awt.Color(191, 191, 191));
        jTextFieldFechaNac.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTextFieldFechaNac.setText(" Lugar de nacimiento");
        jTextFieldFechaNac.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldFechaNac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFechaNacActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 280, 20));

        txtf_FechaNac.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtf_FechaNac.setToolTipText("");
        txtf_FechaNac.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtf_FechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 130, 20));

        jTextFieldGrad.setEditable(false);
        jTextFieldGrad.setBackground(new java.awt.Color(191, 191, 191));
        jTextFieldGrad.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTextFieldGrad.setText(" Grado de instrucción");
        jTextFieldGrad.setToolTipText("");
        jTextFieldGrad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGradActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldGrad, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 150, 20));

        txtf_GradoInst.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtf_GradoInst.setToolTipText("");
        txtf_GradoInst.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtf_GradoInst, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 150, 20));

        jTextFieldGrad1.setEditable(false);
        jTextFieldGrad1.setBackground(new java.awt.Color(191, 191, 191));
        jTextFieldGrad1.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTextFieldGrad1.setText(" Estado Civil");
        jTextFieldGrad1.setToolTipText("");
        jTextFieldGrad1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldGrad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGrad1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldGrad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 130, 20));

        txtf_Edad.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtf_Edad.setToolTipText("");
        txtf_Edad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtf_Edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 140, 20));

        jTextFieldGrad2.setEditable(false);
        jTextFieldGrad2.setBackground(new java.awt.Color(191, 191, 191));
        jTextFieldGrad2.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTextFieldGrad2.setText(" Edad");
        jTextFieldGrad2.setToolTipText("");
        jTextFieldGrad2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldGrad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGrad2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldGrad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 140, 20));

        txtf_EstadCivil.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtf_EstadCivil.setToolTipText("");
        txtf_EstadCivil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtf_EstadCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 130, 20));

        jTextFieldFechaNac1.setEditable(false);
        jTextFieldFechaNac1.setBackground(new java.awt.Color(191, 191, 191));
        jTextFieldFechaNac1.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTextFieldFechaNac1.setText(" Fecha de Nacimiento");
        jTextFieldFechaNac1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldFechaNac1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFechaNac1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldFechaNac1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 130, 20));

        txtf_LugarNaci.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtf_LugarNaci.setToolTipText("");
        txtf_LugarNaci.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtf_LugarNaci, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 280, 20));

        jTextFieldFechaNac2.setEditable(false);
        jTextFieldFechaNac2.setBackground(new java.awt.Color(191, 191, 191));
        jTextFieldFechaNac2.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTextFieldFechaNac2.setText(" Domicilio");
        jTextFieldFechaNac2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldFechaNac2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFechaNac2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldFechaNac2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 550, 20));

        txtf_Domicilio.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtf_Domicilio.setToolTipText("");
        txtf_Domicilio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtf_Domicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 550, 20));

        jTextFieldFechaNac3.setEditable(false);
        jTextFieldFechaNac3.setBackground(new java.awt.Color(191, 191, 191));
        jTextFieldFechaNac3.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTextFieldFechaNac3.setText(" 1° Apellido");
        jTextFieldFechaNac3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldFechaNac3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFechaNac3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldFechaNac3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 140, 30));

        txtf_GrupEtn.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtf_GrupEtn.setToolTipText("");
        txtf_GrupEtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtf_GrupEtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 130, 20));

        jTextFieldGrad3.setEditable(false);
        jTextFieldGrad3.setBackground(new java.awt.Color(191, 191, 191));
        jTextFieldGrad3.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTextFieldGrad3.setText(" Religión");
        jTextFieldGrad3.setToolTipText("");
        jTextFieldGrad3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldGrad3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGrad3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldGrad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 150, 20));

        txtf_Religion.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtf_Religion.setToolTipText("");
        txtf_Religion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtf_Religion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 150, 20));

        txtf_Ocupacion.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtf_Ocupacion.setToolTipText("");
        txtf_Ocupacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtf_Ocupacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 140, 20));

        jTextFieldGrad4.setEditable(false);
        jTextFieldGrad4.setBackground(new java.awt.Color(191, 191, 191));
        jTextFieldGrad4.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTextFieldGrad4.setText(" Ocupación");
        jTextFieldGrad4.setToolTipText("");
        jTextFieldGrad4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldGrad4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGrad4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldGrad4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 140, 20));

        txtf_LugarProced.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtf_LugarProced.setToolTipText("");
        txtf_LugarProced.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtf_LugarProced, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, 130, 20));

        jTextFieldGrad5.setEditable(false);
        jTextFieldGrad5.setBackground(new java.awt.Color(191, 191, 191));
        jTextFieldGrad5.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTextFieldGrad5.setText(" Lugar de procedencia");
        jTextFieldGrad5.setToolTipText("");
        jTextFieldGrad5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldGrad5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGrad5ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldGrad5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 130, 20));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Persona Responsable ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jTextFieldFechaNac4.setEditable(false);
        jTextFieldFechaNac4.setBackground(new java.awt.Color(191, 191, 191));
        jTextFieldFechaNac4.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTextFieldFechaNac4.setText(" Grupo Etnico");
        jTextFieldFechaNac4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldFechaNac4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFechaNac4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldFechaNac4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 130, 20));

        jTextFieldFechaNac5.setEditable(false);
        jTextFieldFechaNac5.setBackground(new java.awt.Color(191, 191, 191));
        jTextFieldFechaNac5.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTextFieldFechaNac5.setText(" 2° Apellido");
        jTextFieldFechaNac5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldFechaNac5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFechaNac5ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldFechaNac5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 140, 30));

        jTextFieldFechaNac6.setEditable(false);
        jTextFieldFechaNac6.setBackground(new java.awt.Color(191, 191, 191));
        jTextFieldFechaNac6.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTextFieldFechaNac6.setText(" Sexo");
        jTextFieldFechaNac6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldFechaNac6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFechaNac6ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldFechaNac6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, 150, 30));

        jTextFieldFechaNac7.setEditable(false);
        jTextFieldFechaNac7.setBackground(new java.awt.Color(191, 191, 191));
        jTextFieldFechaNac7.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTextFieldFechaNac7.setText(" Nombres");
        jTextFieldFechaNac7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldFechaNac7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFechaNac7ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldFechaNac7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, 120, 30));

        txtf_PRApellPat.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtf_PRApellPat.setToolTipText("");
        txtf_PRApellPat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtf_PRApellPat, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 140, 40));

        txtf_PRApellMat.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtf_PRApellMat.setToolTipText("");
        txtf_PRApellMat.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtf_PRApellMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, 140, 40));

        txtf_PRSexo.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtf_PRSexo.setToolTipText("");
        txtf_PRSexo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtf_PRSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 480, 150, 40));

        txtf_PRNombres.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtf_PRNombres.setToolTipText("");
        txtf_PRNombres.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtf_PRNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 480, 120, 40));

        jTextFieldFechaNac8.setEditable(false);
        jTextFieldFechaNac8.setBackground(new java.awt.Color(191, 191, 191));
        jTextFieldFechaNac8.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTextFieldFechaNac8.setText(" Tipo Documento");
        jTextFieldFechaNac8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldFechaNac8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFechaNac8ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldFechaNac8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 140, 30));

        jTextFieldFechaNac9.setEditable(false);
        jTextFieldFechaNac9.setBackground(new java.awt.Color(191, 191, 191));
        jTextFieldFechaNac9.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTextFieldFechaNac9.setText(" Documento");
        jTextFieldFechaNac9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldFechaNac9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFechaNac9ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldFechaNac9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 520, 140, 30));

        jTextFieldFechaNac10.setEditable(false);
        jTextFieldFechaNac10.setBackground(new java.awt.Color(191, 191, 191));
        jTextFieldFechaNac10.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTextFieldFechaNac10.setText(" Número de Celular");
        jTextFieldFechaNac10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldFechaNac10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFechaNac10ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldFechaNac10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 520, 120, 30));

        jTextFieldFechaNac11.setEditable(false);
        jTextFieldFechaNac11.setBackground(new java.awt.Color(191, 191, 191));
        jTextFieldFechaNac11.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTextFieldFechaNac11.setText(" Dirección del domicilio");
        jTextFieldFechaNac11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldFechaNac11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFechaNac11ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldFechaNac11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 520, 150, 30));

        txtf_PRDirecc.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtf_PRDirecc.setToolTipText("");
        txtf_PRDirecc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtf_PRDirecc, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 550, 150, 40));

        txtf_PRNumeroCell.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtf_PRNumeroCell.setToolTipText("");
        txtf_PRNumeroCell.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtf_PRNumeroCell, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 550, 120, 40));

        txtf_PRDoc.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtf_PRDoc.setToolTipText("");
        txtf_PRDoc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtf_PRDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 550, 140, 40));

        txtf_PRTipoDoc.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtf_PRTipoDoc.setToolTipText("");
        txtf_PRTipoDoc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtf_PRTipoDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 140, 40));

        btn_guardar.setBackground(new java.awt.Color(0, 134, 190));
        btn_guardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_guardar.setForeground(new java.awt.Color(255, 255, 255));
        btn_guardar.setText("Guardar");
        btn_guardar.setBorder(null);
        btn_guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 630, 90, 30));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Codigo del Paciente");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 20));

        txtf_CodigoPaciente.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtf_CodigoPaciente.setToolTipText("");
        jPanel1.add(txtf_CodigoPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 180, 20));

        jTextFieldFechaNac12.setEditable(false);
        jTextFieldFechaNac12.setBackground(new java.awt.Color(191, 191, 191));
        jTextFieldFechaNac12.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTextFieldFechaNac12.setText("Número de celular");
        jTextFieldFechaNac12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldFechaNac12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFechaNac12ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldFechaNac12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 270, 20));

        txtf_numCel.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtf_numCel.setToolTipText("");
        txtf_numCel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtf_numCel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 270, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextFieldApellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void btn_SigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SigActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_SigActionPerformed

    private void btn_AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AtrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_AtrasActionPerformed

    private void jTextFieldApellMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApellMatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApellMatActionPerformed

    private void jTextFieldApell2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApell2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApell2ActionPerformed

    private void jTextFieldApell3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApell3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApell3ActionPerformed

    private void jTextFieldFechaNacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFechaNacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFechaNacActionPerformed

    private void jTextFieldGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGradActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGradActionPerformed

    private void jTextFieldGrad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGrad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGrad1ActionPerformed

    private void jTextFieldGrad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGrad2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGrad2ActionPerformed

    private void jTextFieldFechaNac1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFechaNac1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFechaNac1ActionPerformed

    private void jTextFieldFechaNac2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFechaNac2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFechaNac2ActionPerformed

    private void jTextFieldFechaNac3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFechaNac3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFechaNac3ActionPerformed

    private void jTextFieldGrad3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGrad3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGrad3ActionPerformed

    private void jTextFieldGrad4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGrad4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGrad4ActionPerformed

    private void jTextFieldGrad5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGrad5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGrad5ActionPerformed

    private void jTextFieldFechaNac4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFechaNac4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFechaNac4ActionPerformed

    private void jTextFieldFechaNac5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFechaNac5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFechaNac5ActionPerformed

    private void jTextFieldFechaNac6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFechaNac6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFechaNac6ActionPerformed

    private void jTextFieldFechaNac7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFechaNac7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFechaNac7ActionPerformed

    private void jTextFieldFechaNac8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFechaNac8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFechaNac8ActionPerformed

    private void jTextFieldFechaNac9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFechaNac9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFechaNac9ActionPerformed

    private void jTextFieldFechaNac10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFechaNac10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFechaNac10ActionPerformed

    private void jTextFieldFechaNac11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFechaNac11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFechaNac11ActionPerformed

    private void jTextFieldFechaNac12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFechaNac12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFechaNac12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameHistoriaClinicaP1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameHistoriaClinicaP1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameHistoriaClinicaP1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameHistoriaClinicaP1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameHistoriaClinicaP1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_Atras;
    public javax.swing.JButton btn_Sig;
    public javax.swing.JButton btn_guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextFieldApell;
    private javax.swing.JTextField jTextFieldApell2;
    private javax.swing.JTextField jTextFieldApell3;
    private javax.swing.JTextField jTextFieldApellMat;
    private javax.swing.JTextField jTextFieldFechaNac;
    private javax.swing.JTextField jTextFieldFechaNac1;
    private javax.swing.JTextField jTextFieldFechaNac10;
    private javax.swing.JTextField jTextFieldFechaNac11;
    private javax.swing.JTextField jTextFieldFechaNac12;
    private javax.swing.JTextField jTextFieldFechaNac2;
    private javax.swing.JTextField jTextFieldFechaNac3;
    private javax.swing.JTextField jTextFieldFechaNac4;
    private javax.swing.JTextField jTextFieldFechaNac5;
    private javax.swing.JTextField jTextFieldFechaNac6;
    private javax.swing.JTextField jTextFieldFechaNac7;
    private javax.swing.JTextField jTextFieldFechaNac8;
    private javax.swing.JTextField jTextFieldFechaNac9;
    private javax.swing.JTextField jTextFieldGrad;
    private javax.swing.JTextField jTextFieldGrad1;
    private javax.swing.JTextField jTextFieldGrad2;
    private javax.swing.JTextField jTextFieldGrad3;
    private javax.swing.JTextField jTextFieldGrad4;
    private javax.swing.JTextField jTextFieldGrad5;
    public javax.swing.JTextField txtf_ApellMatern;
    public javax.swing.JTextField txtf_ApellPatern;
    public javax.swing.JTextField txtf_CodigoHistClinic;
    public javax.swing.JTextField txtf_CodigoPaciente;
    public javax.swing.JTextField txtf_Documento;
    public javax.swing.JTextField txtf_Domicilio;
    public javax.swing.JTextField txtf_Edad;
    public javax.swing.JTextField txtf_EstadCivil;
    public javax.swing.JTextField txtf_FechaApertura;
    public javax.swing.JTextField txtf_FechaNac;
    public javax.swing.JTextField txtf_GradoInst;
    public javax.swing.JTextField txtf_GrupEtn;
    public javax.swing.JTextField txtf_LugarNaci;
    public javax.swing.JTextField txtf_LugarProced;
    public javax.swing.JTextField txtf_Nombres;
    public javax.swing.JTextField txtf_Ocupacion;
    public javax.swing.JTextField txtf_PRApellMat;
    public javax.swing.JTextField txtf_PRApellPat;
    public javax.swing.JTextField txtf_PRDirecc;
    public javax.swing.JTextField txtf_PRDoc;
    public javax.swing.JTextField txtf_PRNombres;
    public javax.swing.JTextField txtf_PRNumeroCell;
    public javax.swing.JTextField txtf_PRSexo;
    public javax.swing.JTextField txtf_PRTipoDoc;
    public javax.swing.JTextField txtf_Religion;
    public javax.swing.JTextField txtf_Sexo;
    public javax.swing.JTextField txtf_TipoDocumento;
    public javax.swing.JTextField txtf_codigomedico;
    public javax.swing.JTextField txtf_numCel;
    // End of variables declaration//GEN-END:variables
}
